services:
  - type: web
    name: laravel-app
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./docker/php/Dockerfile
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
    startCommand: php-fpm
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql  # MySQLサービス名に変更（Renderでのホスト名）
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel_db
      - key: DB_USERNAME
        value: laravel_user
      - key: DB_PASSWORD
        value: laravel_pass